POST http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTkwMDIyNjEsInVzZXJJZCI6MX0.aQDTw5yhtKlhvVFtSqkBuacJSU3Xds6QBexH1SOojaE